name: geth-classic
version: git
summary: Ethereum Classic's official go-ethereum client.
description: |
  Geth lets you operate a node on the Ethereum Classic network.

grade: devel
confinement: devmode

parts:
  go:
    source-tag: go1.10.3
  geth:
    after: [go]
    source: .
    plugin: go
    go-importpath: github.com/ethereumproject/go-ethereum

apps:
  geth:
    command: bin/geth

