name: geth
version: git
summary: Ethereum Classic's Official go-ethereum client.
description: |
  Geth lets you operate a node on the Ethereum Classic network.

grade: devel
confinement: devmode

parts:
  geth:
    source: .
    plugin: go
    go-importpath: github.com/ethereumproject/go-ethereum

  apps:
    geth:
      command: geth

